### PR TITLE
Seed database with data from the downloaded archives

### PR DESCRIPTION
**Pull request by ri72miieop**
I removed the previous script to import from the github releases data.

New method uses data downloaded using `scripts\download_storage_anon.mts`. There are some issues with importing some records (which can be verified using pnpm dev:validateimport), but from what I've seen it's <0.1% of records, so this should not have a major impact in dev scenarios.

### CODE REVIEW

**Comment by ri72miieop** [comment]
created new migration to grant `service_role` permissions for `private` schema and `private.job_queue`, this PR now fixes #156

**Comment by ri72miieop** [comment]
these changes solve issue #160 the user can download data with `pnpm dev:downloadarchive` and then `pnpm dev:importfiles` to import them into the db. Environment variable ARCHIVE_PATH needs to be set to the root path where the archive was downloaded.

**Comment by TheExGenesis** [comment]
@ri72miieop remember to run `pnpm build` to make sure deployment will build

image

**Comment by ri72miieop** [comment]
my bad, I will look into how to setup a pre-push hook so it double-checks before pushing (or checks it if I forget!)

I fixed the errors now.

**Pull request merged**
