### PR TITLE
Store latest archive only

### PR DESCRIPTION
**Pull request by DefenderOfBasic**
Storage URLs are currently of the form:

```
/username/timestamp.json
```

This changes it to

```
/username/archive.json
```

This simplifies things, don't need to keep all versions, just the latest. And makes the URLs more predictable for consumers. 

I was trying to work on a script to rename the past stuff already uploaded to storage, but couldn't get `download_storage.mts` script working (due to lack of service role?) What would be the best workflow for this? Should be pretty simple I think, just:

- list all objects
- find the latest date for each username
- cp it to `/username/archive.json`

could stop there, leave the old data in, or confirm this works/successfully copied, then delete the old stuff

### CODE REVIEW

**Comment by TheExGenesis** [comment]
don't need a service role, could just use the anon key, but i'll do it

**Comment by TheExGenesis** [comment]
Hey Defender next time I hope you can test stuff in a local db.

- I renamed the existing storage archives and the users w multiple files failed because the name would've been duplicated, so I had to manually pick the latest one for each user and rename them.
- The uploadToStorage function needs an update to [replace an existing file](https://supabase.com/docs/reference/javascript/storage-from-update) instead of failing to update if there's a duplicate

**Comment by DefenderOfBasic** [comment]
Thanks for the review @TheExGenesis ! I think this is an important feature for people building on top of the archive, I don't know if I'll have a chance to setup the local DB/address this this week, but if anyone else wants to finish it up before I get to it feel free to.

**Comment by TheExGenesis** [comment]
I finished it, it was relatively quick

**Pull request merged**
